POS/POS/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('base.urls')),
    path('', views.showOrder, name='showOrder'),
    path('createtable/', views.create, name="createtable"),
    path('update/<int:id>', views.update, name="update"),
    path('endtable/<int:id>', views.endtable, name="endtable"),
    path('showresults/', views.showresults, name="showresults"),
    path('updateresult/<int:id>', views.updateresult, name="updateresult"),
    path('deleteresult/<int:id>', views.deleteresult, name="deleteresult"),
]

POS/base/urls.py
from django.urls import path
from .views import *
app_name = "base"
urlpatterns = [
    path('login/',login,name="login"),
    path('logout/',logout,name="logout"),
]

POS/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('base.urls')),
    path('', views.showOrder, name='showOrder'),
    path('createtable/', views.create, name="createtable"),
    path('update/<int:id>', views.update, name="update"),
    path('endtable/<int:id>', views.endtable, name="endtable"),
    path('showresults/', views.showresults, name="showresults"),
    path('updateresult/<int:id>', views.updateresult, name="updateresult"),
    path('deleteresult/<int:id>', views.deleteresult, name="deleteresult"),

]

POS/base/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

POS/base/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect
from django.contrib import auth
from django.contrib.auth.models import User

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(request, username=username, password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('showOrder')
        
        else:
            return render(request,'base/login.html')     
    elif request.method == 'GET':
        return render(request, 'accounts/login.html')
    

def logout(request):
    auth.logout(request)
    return redirect('showOrder')

POS/base/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="loginform">
    <img id="first" src="https://i.ibb.co/GTM7mCc/IMG-8941.png">

    <form action="{% url 'base:login' %}" method="POST">
        {% csrf_token %}
        <div id="user_id">
            <input id="inputID" type="text" name="username" placeholder="ID"><br>
        </div>
        <div id="user_pw">
            <input id="inputPW" type="password" name="password" placeholder="Password"><br>  
        </div>

        <div id="loginbutton">
            <input id="inputlogin" type="submit" value="로그인">
        </div>
    </form>
</div>
{% endblock %}

POS/base/templates/accounts/logout.html
{% extends "base.html" %}

{% load static %}


{% block content %}

<form action="{% url 'base:logout' %}" method="POST">
    {% csrf_token %}
    <p>로그아웃 하시겠습니까?</p>
    <input type="submit" value="로그아웃">
</form>

{% endblock %}